[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

# Redirect riveraprollc.com to www.riveraprollc.com
[[redirects]]
  from = "https://riveraprollc.com/*"
  to = "https://www.riveraprollc.com/:splat"
  status = 301
  force = true

# Existing SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200